### ISSUE TITLE
Diffs are not shown in vscode

### ISSUE THREAD

**Issue by berhalak** [xpodev/local-history#1]
Diffs are created in the .lh folder, but the ui doesn't show anything.
My vscode:

Version: 1.56.1
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:16.954Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic snap

**Comment by neriyaco** [comment]
You need to select the file in the Local History tab in the activity bar.
If you still don't see it, can you please tell me exactly what to do so I can reproduce this?

**Comment by berhalak** [comment]
I think that something is wrong with the extension at the market. When I build it from source and install locally, it works as you described.

**Comment by neriyaco** [comment]
I updated the extension, let me know if it's working now.
