### ISSUE TITLE
[feature request] ignored files for all the workspace

### ISSUE THREAD

**Issue by tgaochn** [xpodev/local-history#12]
Current ignored files stored in .lh/.lhignore are workspace-specific.
Is it possible to have a universal config to ignore some files for all the workspace?
For example, I'd like to avoid history files of *.csv for all my projects without modifying the separate config files.
Thanks.

**Comment by neriyaco** [comment]
Hi,
Check #8 
You can add the global ignored files under `~/.lh/.lhignore`
