### ISSUE TITLE
Faster way to get to diffs for current file.

### ISSUE THREAD

**Issue by crispinb** [xpodev/local-history#2]
Nice extension, thanks. Currently it's ergonomically a bit awkward to see changes for the current file: open the local history view & click possibly several levels down the file tree. It would be very handy to have a command to focus on the diffs view for the file in the currently active editor. 

I also suggest that when the diffs view is focussed, keyboard focus stays there while the user hits arrow keys to see the next/previous diffs, with a keyboard shortcut to jump back to the active editor once the required diff has been surfaced.

**Comment by neriyaco** [comment]
I will look into it
Thanks
