### ISSUE TITLE
Nothing is showing in VSC local history

### ISSUE THREAD

**Issue by pronovaso** [xpodev/local-history#4]
Hi.

I install last version of this extension from official market place. Everything looks alright,but nothing is showing in history.In lh folder are files which I changed.

**Comment by neriyaco** [comment]
Hi,
In which view you can't see anything? The browser view or the diff view?
Can you give me the steps to reproduce the problem?

Thanks :)

**Comment by pronovaso** [comment]
Hi.

I don't understand but now I can see changes in file and in diffs too. Sorry for the issue, maybe I was blind :-)
