### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by ilteoood** [xpodev/local-history#5]
Hi,
I'm trying to use the extension.

I see the diff created in the `.lh` folder:

![image](https://user-images.githubusercontent.com/6383527/140089645-85b3b3ee-1788-4055-935f-a25d1c98abff.png)

But when I try to check them in the dedicated tab, nothing appear:

![image](https://user-images.githubusercontent.com/6383527/140089741-e87ee931-2f2d-4885-9f29-8084258fc0b0.png)

**Comment by neriyaco** [comment]
Hi, sorry for the late response
Did you choose the right file in the browser?
Also, you can focus the diff with CTRL+SHIFT+ALT+D
If it's still doesn't work can you please tell me how to reproduce the problem? Thanks.

**Comment by neriyaco** [comment]
I'm closing this issue since there's no response.
If the problem still exists you can reopen it.
