### ISSUE TITLE
Auto select current file

### ISSUE THREAD

**Issue by niktor76** [xpodev/local-history#6]
Hi, I love your extension. It is very helpful.
I wish the extension would automatically switch to the history of the current file.

**Comment by neriyaco** [comment]
Hi, thank you!
You can use CTRL+SHIFT+ALT+D to open the diff tab for the current file

**Comment by niktor76** [comment]
Hi, I am using MacOS. Which command is this exactly? I have always go to the local history browser to select the file.

**Comment by neriyaco** [comment]
Hi,
I checked and I didn't add the shortcut from MacOS.
Will add it in the next version.
Until then you can set the shortcut for yourself under Preferences > Keyboard Shortcuts
the command name is `Local History: Open Diff (local-history.open-diff)`

**Comment by tgaochn** [comment]
> Hi, I checked and I didn't add the shortcut from MacOS. Will add it in the next version. Until then you can set the shortcut for yourself under Preferences > Keyboard Shortcuts the command name is `Local History: Open Diff (local-history.open-diff)`

but this command will only open Local History tab without selecting the current file.

**Comment by niktor76** [comment]
> Hi, I checked and I didn't add the shortcut from MacOS. Will add it in the next version. Until then you can set the shortcut for yourself under Preferences > Keyboard Shortcuts the command name is `Local History: Open Diff (local-history.open-diff)`

This works also an MacOS. Thanks, that's very helpful.
It would be great if this would be happening automatically. Then it will be perfect!
