### ISSUE TITLE
.lhignore wrong EOL

### ISSUE THREAD

**Issue by ghost** [xpodev/local-history#7]
Hi,

The .lhignore file is created with LF mode on Windows.
However, the EOL used to split the lines is CRLF. So the settings do not work as expected.

If the extension uses the newline of the OS, the file should be created with the corresponding EOL or be compatible with both.

Thanks

**Comment by neriyaco** [comment]
Hi

I did not understand what is the problem is exactly.
Can you tell me what OS do you use and how to reproduce this issue?

**Comment by ghost** [comment]
Windows 10, animated gif below to reproduce the bug. Settings in .lhignore will not work by default on Windows, the file must be changed to CRLF.

```
//on windows EOL = CRLF
import { EOL } from 'os';

//can't split because will use CRLF on LF file
await FileSystemUtils.readFile(this.ignoreFile)).split(EOL)
```

![eol](https://user-images.githubusercontent.com/89488477/143787211-c9439977-fb7e-46bd-ae4e-13b0cc197b17.gif)
