### ISSUE TITLE
Feature Request: Add configuration for directory where history is saved

### ISSUE THREAD

**Issue by BishalTS** [xpodev/local-history#9]
Ability to change directory where the `.lh` folder and all the history is saved.

**Comment by neriyaco** [comment]
Hi,
This is a bit of a problem, how the extension would know where to look for the `.lh` folder?
If you have an idea I would love to hear it.

**Comment by arvislacis** [comment]
For this to work there should be a new setting which allows to set the root path/directory in which the `.lh` folder and all substructure is created. If this setting isn't set or is null/false then extension uses the default behavior and  uses the `.lh` folder in project root.

Although probably there is another problem - VSCode probably will not allow to specify or write in other directory which is not under the project structure. Anyways, my mentioned approach would work if user would like to save history somewhere under the project, for example, `./.vscdoe/` or `./dev-files/` etc.

**Comment by neriyaco** [comment]
I'll look into it, thanks.

**Comment by T1MOXA** [comment]
Here's how such an option is implemented in a similar extension
https://github.com/zabel-xyz/local-history/blob/0543d2d06645e3434e4372b45f53a5dc80eb1f00/src/history.controller.ts#L212

**Comment by MostHated** [comment]
I definitely need this feature, as when I am using VSCode for work, there are some mounted locations in which the service account I am using does not have access to the mounted drives root, so history cannot be saved here. 

The way I had been working in the past is I have my workspace file saved in a nested directory several levels down and I just open it manually. The other 'local history' extension I was using before (which was mentioned above) let me save the path within my workspace settings file and it just got it from there, and there was a setting which let me globally disable local history unless I was working in a workspace which had the manual path set, which was ideal for my particular situation.

**Comment by neriyaco** [comment]
I kind of stopped maintaining this extension because there is a local history built into vscode

**Comment by MostHated** [comment]
Oh, is there? It must be new? I didn't even realize there was that feature now.

**Comment by neriyaco** [comment]
They added it here
https://code.visualstudio.com/updates/v1_44#_timeline-view

**Comment by MostHated** [comment]
Ah, I guess I never noticed it because it does not work with how my VSCode needs to be configured. So it looks like I need to stick with an extension of some sort either way. I appreciate the information.

![](https://img.instance.id/jkWWdgNpRkrA/direct)

**Comment by neriyaco** [comment]
I can add this feature, it'll take couple of days because I'm busy with other stuff

**Comment by MostHated** [comment]
Oh, man, that would be great. No worries, I definitely understand being busy. I definitely appreciate it. :+1:

**Comment by neriyaco** [comment]
Sorry for the long wait, I added this functionality and will be available next update.
